### ISSUE TITLE
Keyboard shortcut selection regarding Rmarkdown ?

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#116]
idea looking at this SO question 
https://stackoverflow.com/questions/30938280/keyboard-shortcut-to-produce-code-chunk-brackets-in-markdown-in-r-for-rstudio

We could have a page on a curated keyboard shorcut reference regarding Rmarkdown only.

**Comment by dr-harper** [comment]
Good idea! There is a full list of keyboard shortcuts for RStudio here: https://support.rstudio.com/hc/en-us/articles/200711853-Keyboard-Shortcuts
