### ISSUE TITLE
Footer on every page in Latex

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#119]
Related to this question 
https://stackoverflow.com/questions/30922602/creating-a-footer-for-every-page-including-first-using-r-markdown

**Comment by dr-harper** [comment]
This is a slight expansion to #56, and therefore will fit in to the section on LaTeX header and footers: https://dr-harper.github.io/rmarkdown-cookbook/add-custom-headers-and-footers.html

**Comment by dr-harper** [comment]
Relatively easy one to address. I have added a subsection the the existing section, but could potentially integrate at a later date.

Close the issue if you are happy 😄

**Comment by cderv** [comment]
I want to complete a bit this chapter. I'll do a small PR. 

One question though : Should pandoc variable `header-includes` be preferred over `include` argument in pdf document as explained [in the definitive guide](https://bookdown.org/yihui/rmarkdown/pdf-document.html#includes-1) ?
It is either one or the other. You can't use both. There is already a conflict with HTML format (see rstudio/rmarkdown#816). I tested it and I can confirm it is the same with `pdf_document` if we provide both. 

I think it could be a good idea to precise that, and to show also how to create a header.tex file from inside the Rmd. (`\\` required to escape `\`)

```r
---
title: "Test"
author: "Author Name"
output: 
  pdf_document:
    includes:
      in_header: header.tex
---

```{r, include = FALSE}
header <- "\\usepackage{fancyhdr}
\\usepackage{lipsum}
\\pagestyle{fancy}
\\fancyhead[CO,CE]{This is fancy header}
\\fancyfoot[CO,CE]{And this is a fancy footer}
\\fancyfoot[LE,RO]{\\thepage}
\\fancypagestyle{plain}{\\pagestyle{fancy}}"
writeLines(header, "header.tex")
```

\lipsum[1-30]
```

 what are your thoughts on `header-includes` vs `pdf_document: includes : in_header` ?

**Comment by dr-harper** [comment]
Good point. I had so far used the `header-includes` as it makes it easier to produce self-contained examples for the book. But I tend to use an external LaTeX file for most of my own customisations as the `header-includes` method can quickly become too much. 

I propose that we start the LaTeX chapter with an explanation of the methods available, and the benefits/ disadvantages of using each approach.

**Comment by cderv** [comment]
> I propose that we start the LaTeX chapter with an explanation of the methods available, and the benefits/ disadvantages of using each approach.

I agree. It should be noted that `header-includes` pandoc variable and `includes` arg of `pdf_document` is also working with other format like `html_document`, where it could be useful to add to the `in_header`, or `before_body` or `after_body`. So, we should see if it fits in Latex part or more general one explaining this `includes` feature in more detail. perhaps with template mechanism ? 🤔
