### ISSUE TITLE
How to hide message, warning, results, ... 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#12]
**How to customise what is printed by a chunk?**

# per chunk 
Add a chunk option in `{r chunk-name, name = value}`
* hide message: `message = FALSE`
* hide warning: `warning = FALSE`
* hide all : `include = FALSE`
* hide results : `results = "hide"` or `results = FALSE`

# All document
Same options but define a setup chunk with global options
```r
knitr::opts_chunk$set(message = FALSE)
```
## SO question

- [ ] https://stackoverflow.com/questions/13090838/r-markdown-avoiding-package-loading-messages
- [ ] https://stackoverflow.com/questions/46850633/why-does-ggplot-not-allow-suppressing-of-messages-generated-by-its-geoms
- [ ] https://stackoverflow.com/questions/47710427/how-to-show-code-but-hide-output-in-rmarkdown
- [ ] https://stackoverflow.com/questions/23189012/how-do-i-suppress-the-warning-from-including-a-library-when-using-knitr-in-r

## Related knitr example

* https://github.com/yihui/knitr-examples/blob/master/007-text-output.Rmd

## Related chapter in the book

* https://dr-harper.github.io/rmarkdown-cookbook/customising-knitr-options.html

## Related knitr example

- [Demo](https://yihui.name/knitr/demo/output#one-comment-on-messages)

**Comment by mikey-harper** [comment]
This is explained within the R Markdown book [here](https://bookdown.org/yihui/rmarkdown/r-code.html), so I would want to make sure this adds some value to the existing guidance.

Perhaps we can add a few recipes for how to use this in practice? For example, if we wish to disable messages for the whole document we can set the options via `knitr::opts_chunk$set()`, or if we just want it for an individual chunk we can set it in the chunk header.

I will draft this up over the coming week :)

**Comment by dr-harper** [comment]
Also relevant to this: https://stackoverflow.com/questions/13091112/hiding-the-r-code-in-rmarkdown-knit-and-just-showing-the-results/52589123#52589123

Added an answer to the post which will form an outline for the book.

**Comment by AtomicNess123** [comment]
I'd like to hide all warnings and error messages of my faulty code for educational purposes (students must tell if a code chunk is correct or not). How to implement this? When I knit my faulty code I get this:

![screenshot_ 2021-07-09 at 15 32 49](https://user-images.githubusercontent.com/47029233/125078516-280f3400-e0cb-11eb-90c0-2871021bae06.jpg)

**Comment by cderv** [comment]
Hi, 

Please next time, follow the issue guide: https://yihui.org/issue/#got-a-question
It is best to ask question in Q&A places than in closed issues. 

Also, you asked question in the closed issue of a repo of a book. So you can just read the book related content: https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html

The solution for you should be in the page.

**Comment by jmouchnino** [comment]
How to hide message in a R Script ? A global solution would be good

`options(warn = -1)` dose not suppress messages such as 

```
`geom_line()`: Each group consists of only one observation.
ℹ Do you need to adjust the group aesthetic?
```

**Comment by cderv** [comment]
@jmouchnino this is not a warning I think
https://github.com/tidyverse/ggplot2/blob/f7246d4ad9aeee46890f60e3821d762f390378ed/R/geom-path.R#L156-L161

and also `warn` is a usual R option. the chunk options are described in https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html

You can use them to hide the proper form of what is printed (message, warning or error=

**Comment by cderv** [comment]
I see you asked also on **rgbif** repo - please do link when you open in multiple places. 
- https://github.com/ropensci/rgbif/issues/802

It seems they use `cat()` to print this message so it can't be hidden with standard options. 
https://github.com/ropensci/rgbif/blob/c94c95a8d115ea0b946a536f6d304f0ff39cdf30/R/occ_download.R#L237-L261

The only thing you can do at **knitr** level is hide the cell completely (`include = FALSE`). The source code won't show in this case

`message = FALSE` would work if they were using `message`, but not with `cat()`. 

Maybe we could find some more tricks, but this should be a feature request in https://github.com/ropensci/rgbif to be able to hide the message in **knitr** context or in all context. 

Either using a global option to prevent printing this or use a `knit_print.occ_download()` method that would take some dedicated cell option to adapt what is printed. 

Anyhow, this is in their hand I believe - happy to help there if I can.

**Comment by veronicar239** [comment]
@cderv ah yes apologies I forgot to link the issue opened in rgbif (since it's not ideal to add a comment to a closed issue). 

I did use include = FALSE in the Rmarkdown chunk but the gbif download message is still printed in both html and PDF outputs. 

```{r data-download, include=FALSE}
# Create download request
download_key <- occ_download(pred_or(pred("institutionCode", "USNM"), pred("institutionCode", "US"),pred("institutionCode", "smithsonian institution, national museum of natural history"),pred("institutionCode", "nmnh"),pred("institutionCode", "smithsonian institution"),pred("institutionCode", "usnc"),pred("institutionCode", "STRI"),pred("institutionCode", "SCZ"),pred("institutionCode", "SERC"),pred("institutionCode", "USNMENT")))
```

Would you have any other ideas how to silence this from being printed?

**Comment by cderv** [comment]
I can't try **rgbif** because I don't have access, but I did a dummy test considering their printing method

and `include=FALSE` do hide, and also assigning should not print. 

````markdown
---
title: "Untitled"
date: "`r Sys.Date()`"
output: html_document
---

## Load rgbif

```{r}
library(rgbif)
```


# Prints

```{r}
test <- structure(list(), class = "occ_download")
test
```

# do not print

```{r}
library(rgbif)
test <- structure(list(), class = "occ_download")
```

# is not included

The same code cell that was printed is now no more printed when `include = FALSE`

```{r include=FALSE}
test <- structure(list(), class = "occ_download")
test
```

````

<img width="1001" height="1032" alt="Image" src="https://github.com/user-attachments/assets/92c9df7b-d906-423d-9384-ab40934bed41" />

So I am not sure what is happening in your case. This would need to be reproduced in some context. Having a full document reprex can help know the specific context (I used `html_document()` format here.

**Comment by yihui** [comment]
@veronicar239 I'm very surprised that you still get output even with `include = FALSE`. This option will make sure absolutely nothing from the code chunk will be included in the output. A full reprex can be helpful for us to understand how this can possibly happen.

**Comment by veronicar239** [comment]
Thank you @cderv for helping to look into all of this. Indeed you are correct - there are different messages being printed occ_download() and occ_download_wait(). I added `include = FALSE` to each chunk/command and it has successfully hidden any output messages. Thank you!
