### ISSUE TITLE
How to use the `child` option to reuse Rmd hunk in several documents

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#14]
Another [blog post](https://www.garrickadenbuie.com/blog/2018/03/05/dry-vignette-and-readme/) inspired this. 

I knew the `child` option to reuse some code chunk, but I find this use case very interesting : For a 📦 developer, reuse some identical part in README, Vignette and Blogpost without copy pasting or repeating yourself.
Applied in [vetr](https://github.com/brodieG/vetr/tree/master/vignettes/rmdhunks) package.

Looks to me that a recipe candidate to this book.

**Comment by cderv** [comment]
Also the related, this SO question
https://stackoverflow.com/questions/25824795/how-to-combine-two-rmarkdown-rmd-files-into-a-single-output

Use `child` chunk option to add, in a main Rmd document, some chapters wrote in Rmd files without yaml header. See SO answer.

However, for this use case, this is better to refer to `bookdown::pdf_document2`, `bookdown::html_document2`,  `bookdown::work_document2` and others. (As in your answer on SO @mikey-harper)

**Comment by mikey-harper** [comment]
I agree this would be a really good thing to add. I think explaining the use cases for using child documents against bookdown will be really useful.

I have marked this as one of my top priorities to add.

**Comment by cderv** [comment]
About `child` option and `knit_child`
https://stackoverflow.com/questions/17593912/insert-portions-of-a-markdown-document-inside-another-markdown-document-using-kn

**Comment by dr-harper** [comment]
I have added a first draft of this here: https://dr-harper.github.io/rmarkdown-cookbook/multi-file-documents.html . I think it is one I want to come back to in the future though to revise.

**Comment by cderv** [comment]
I agree this a part that could be adjust in the future. I find the example of using child document in package development to reuse some common part in Readme, blog post and vignette is interesting. And worth mentioning with details. But it may be be too odd use case :thinking:

**Comment by cderv** [comment]
> I think it is one I want to come back to in the future though to revise.

I added some content too. Should we put a tag on closed issue we think we may need to come back later ?

**Comment by cderv** [comment]
Addition to child document b9879d6

**Comment by yihui** [comment]
@cderv Thanks for taking care of closing issues! So far I have been mostly writing whatever I want to write without looking at the existing Github issues. In the future, when I actually start looking at the issues, I'll put `close #xxx` in the commit messages to automatically close issues.

**Comment by cderv** [comment]
No worries. It is fine by me to keep on doing that. As I understood how you are currently working (not looking at issues :wink:), it is the way I can be useful while you finish including all you have in mind ! I also know that way all the topic you are covering and it helps having a broader pictures !

Also, when we will go one by one on issues, we'll know what has been added and if we can close or if something missing. I find it useful to keep links on issues and code. 

When ready, we will switch on a more issue-based content addition and I hope I'll be able to help you on some parts. 😉
