### ISSUE TITLE
How to exit compilation early from a Rmd document

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#141]
Use not well know `knit_exit`
https://github.com/yihui/knitr-examples/blob/master/096-knit-exit.Rmd

The rest of the document after `knit_exit()` is ignored.

**Comment by dr-harper** [comment]
Cool feature, and one I hadn't seen. I have added this in commit 2f18b11efcbe6eaeadd5fae201a4e31169bff287

**Comment by cderv** [comment]
Perfect! Thanks!
