### ISSUE TITLE
How to have subfigure in Latex ouput

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#142]
use package _subcaption_ from Latex
https://github.com/yihui/knitr-examples/blob/master/104-subfigure.Rnw

**Comment by dr-harper** [comment]
Not sure whether this has been sufficiently covered in this post: https://dr-harper.github.io/rmarkdown-cookbook/latex-subfigures.html 

The current solution uses the `subfig` package. It might be one of those cases where there are multiple packages which do a similar thing in LaTeX with little difference. This post suggests that `subcaption` might be a better way forward. 

Will try playing around with this to see.

**Comment by dr-harper** [comment]
Right, having played around with this I think I am going to leave it out. Knitr only has built in support for the `subfig` package, as explained by [Yihui](https://yihui.name/knitr/options/)

> fig.subcap: (NULL) captions for subfigures; when there are multiple plots in a chunk, and neither fig.subcap nor fig.cap is NULL, \subfloat{} will be used for individual plots (you need to add \usepackage{subfig} in the preamble); see 067-graphics-options.Rnw for an example.

I am trying to avoid using the `.Rnw` format throughout the book. I think it is generally more confusing for new users and there is limited merit to using this format when you can used `.Rmd`.  

I will let you close the issue if you are happy 😄actually, I have been thinking that we should make it habit that if one of us posts a solution to an issue, we should let the other person close it out. That way we can make sure that both of us are happy with the change.

**Comment by cderv** [comment]
Thanks for testing. One way to do it is enough. 

And several knitr example are old and concerns Rnw. It is not obvious of they are still suitable for Rmd. This book and repo will clarify that.

**Comment by cderv** [comment]
> I have been thinking that we should make it habit that if one of us posts a solution to an issue, we should let the other person close it out. That way we can make sure that both of us are happy with the change.

And I agree on that.

**Comment by piiskop** [comment]
How to increase spacing between subfigures? The subcaptions have no space in between.
