### ISSUE TITLE
What to do to have examples folder for the book ?

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#150]
following a discussion in  #47 

Currently, as we have `rmd_subdir: true` in `_bookdown.yml`, all the Rmd in the _examples_ subdirectory are rendered in the book ([chapter 15](https://dr-harper.github.io/rmarkdown-cookbook/eval-after.html#)). I think you notice, right ? 

There is no mechanism to ignore directories (yet because I am 🤔 about a PR to bookdown), just a mechanism to select which subdirectories to look at. I see several options then: 

* Provide the list of subdirectories and ignore _examples_
* move the _example_ directory in a companion repository (`rmarkdown-cookbook-examples` ❔ )
* `rmd_subdir: false` and not use Rmd in subdirectory for the book. Only full rmd, one per chapter or anything, but all in root directory
* `rmd_subdir: "book_rmd"` and move everything related to the book Rmd into one subdirectory.

We have to think about that.

**Comment by dr-harper** [comment]
Yeah, noticed this problem and couldn't see an immediate solution. So thanks for your ideas!

Option two actually seems like the best idea to me. Will make this change now.

Ultimately, the structure might change to remove some of the subdirectories. It was just a way for me to try and get some order to the project, and to make it easy for us to reorganise things if we want to move content from one chapter to another.

**Comment by dr-harper** [comment]
Just merged this change within commit ec1c4932db0c83d87b6651ddbe6d66ea2b8cafdb. Will let you close it if you are happy: it seems to be working well for me though

**Comment by cderv** [comment]
Ok so option 5 !!  😉 

Seems ok ! Thank you !!
