### ISSUE TITLE
document the knit undocumented hook

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#151]
If we do a part about rstudio integration, it could be the opportunity to document this undocumented yaml argument that help customized the beahaviour of the knit button. 

There is a `knit:` yaml field that can contain a **one-liner** function with two arguments : `inputFile` and `encoding`. If detected by RStudio IDE, the knit button will execute this function. 

Example for rendering with the date in output file

```yaml
---
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile),'/', format(Sys.Date(), "%Y%m%d"), '-', tools::file_path_sans_ext(basename(inputFile)), '.html')})
---
```

Used in [slidify](https://github.com/ramnathv/slidify/commit/07794a3c2d228822c173c1ad5eacf5ab54a42062)

**Comment by dr-harper** [comment]
This is awesome! I was about to suggest that you could make a function out of this and store it as in a package so that you don't have to add so much code to the YAML. Then I clicked on the link and saw this is exactly what slidify does!

Will definitely add this

**Comment by dr-harper** [comment]
Playing around with this, you can have multi-line statements if you start each new line with 4 spaces. This definitely keeps things more readable:

```yaml
---
knit: (function(inputFile, encoding)
    {rmarkdown::render(input = inputFile,
    encoding = encoding,
    output_file = paste0(tools::file_path_sans_ext(basename(inputFile)),
                                         '-',
                                         format(Sys.Date(), "%Y%m%d"),
                                         '.html'))})
---
``` 
Have posted a draft in d98263d. Let me know if you have any thoughts.

**Comment by cderv** [comment]
This is covered by d98263d in current chapter 12.
