### ISSUE TITLE
Replace kable column names

### ISSUE THREAD

**Issue by dr-harper** [dr-harper/rmarkdown-cookbook#161]
I have been surprised how much traffic this answer is getting on SO, so would be something that is useful to include: https://stackoverflow.com/questions/51432502/replace-column-names-in-kable-r-markdown/51444998#51444998

**Comment by dr-harper** [comment]
Related to #2

**Comment by dr-harper** [comment]
Added some draft content in 8e9ccf8aadb9cd9ce6b5b1055faf56aa16fb2d61.

**Comment by cderv** [comment]
I think we can close now ?
