### ISSUE TITLE
4.1 Changing Font Colour

### ISSUE THREAD

**Issue by msmall318** [dr-harper/rmarkdown-cookbook#175]
colorize = function(x, color){
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}(%s)", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<font color='%s'>%s</font>", color, x)
  } else x
}

should be brackets not parantheses for the latex output

colorize = function(x, color){
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{%s}{%s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<font color='%s'>%s</font>", color, x)
  } else x
}

**Comment by cderv** [comment]
Thank you @msmall318 for reporting ! 

I took your finding in a PR. Do not hesitate to open one for such typo finding 😄
