### ISSUE TITLE
Recipes about new custom block features

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#179]
See https://github.com/rstudio/rmarkdown/commit/cecd812743826989b539a7b0fcb1b8c08f09c05d and https://github.com/yihui/bookdown-crc/issues/1#issuecomment-533686381

This relates to already closed #50 

I think an examples of this new feature would be useful in this book, and also how it relates to the existing one.

**Comment by yihui** [comment]
Yes, I have been working on this. I'll delete the current content on `block` and `block2`.

**Comment by bnicenboim** [comment]
Sorry, is there an example somewhere? Some Rmd somewhere in github?

**Comment by cderv** [comment]
Currently you can access the development version of this book 
https://bookdown.org/yihui/rmarkdown-cookbook/

You'll find a part on custom block in this chapter
https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html

The book is still in creation so things may change but this part as already been rewrite once so informations are pretty up-to-date

**Comment by bnicenboim** [comment]
Great!, should it work out of the box in bookdown?

the "hello world" example works for me in regular rmarkdown but in bookdown it prints the :::
