### ISSUE TITLE
Digging out the itsy-bitsy features in kable()

### ISSUE THREAD

**Issue by yihui** [dr-harper/rmarkdown-cookbook#2]
e.g., https://github.com/yihui/knitr/issues/1585

Honestly even I don't remember all features I have provided in this function...

**Comment by mikey-harper** [comment]
Thanks for redirecting the issues.  Please keep them coming if you have any others which you think would make good content!

Agree this is a fantastic idea, and gives a good concept to frame a section of the book around. So many SO questions relate to` kable`.

**Comment by yihui** [comment]
We should invite @haozhu233 to write the chapter on tables. He is well-known as the "kable guy" now: https://twitter.com/haozhu233/status/1024346015774597120 😁

**Comment by haozhu233** [comment]
@yihui 😂 Sure. I would love to make some contributions here. Thanks for the invite! 👍

**Comment by cderv** [comment]
Adding a already covered SO question 
https://stackoverflow.com/questions/49015578/space-after-every-five-rows-in-kable-output-with-booktabs-option-in-r-markdown
