### ISSUE TITLE
How to allow duplicate labels ?

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#21]
Not found in a SO question at first but a feature I just discovered reading the source of `html_notebook`.
See the related [knitr GH issue](https://github.com/yihui/knitr/issues/957)

This option can be set to allow duplicate label, 

```r
options(knitr.duplicate.label = 'allow')
```
and duplicate chunk will be differenciated with a number. Drawbacks: all figures and other ressources also.

A trick that could find its place in the cookbook.

## Related SO question

* https://stackoverflow.com/questions/51191677/can-i-check-for-duplicate-labels-before-knitting-the-whole-document-using-knitr
* https://stackoverflow.com/questions/36868287/purl-within-knit-duplicate-label-error/47065392#47065392

**Comment by dr-harper** [comment]
I have been thinking this one through and don't want to encourage it as a first choice, as the default behaviour of not allow duplicates is useful in most cases.  But the example given in the GH issue provides a compelling enough reason to explain this for some use cases.

**Comment by dr-harper** [comment]
I have added a first version in here: https://dr-harper.github.io/rmarkdown-cookbook/allow-duplicate-code-chunks.html
