### ISSUE TITLE
How to change the font color ? 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#24]
* Use style in an html tag
* Use latex syntax `\textcolor`
* Use a custom function to deal with multiple output. Something like 
```r
format_with_col = function(x, color){
  if(knitr::is_latex_output())
    paste("\\textcolor{",color,"}{",x,"}",sep="")
  else if(knitr::is_html_output())
    paste("<font color='",color,"'>",x,"</font>",sep="")
  else
    x
}
```
then ``` `r format_with_col("text", "red")` ```

## Related SO question

* https://stackoverflow.com/questions/29067541/rmarkdown-how-to-change-the-font-color

**Comment by dr-harper** [comment]
I have added this to the new chapter on formatting: https://dr-harper.github.io/rmarkdown-cookbook/changing-font-colour.html

I included a bit justifying the benefit of designing for multiple outputs. I think it would be best to spin this out into a detailed explanation near the start of the book.

**Comment by RLesur** [comment]
Sorry to bring bad news because you are doing a great work. 
The `<font>` element is obsolete in HTML5 and its support could be removed at any time by browsers. CSS must be used instead.
See for instance https://developer.mozilla.org/docs/Web/HTML/Element/font

**Comment by cderv** [comment]
Thanks for the head up. We clearly need to change that. and double check any other recipe...
