### ISSUE TITLE
How to add numbered figure caption in a document ? 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#25]
This is an old question than know have an answer with bookdown, but can also be dealt without it. Should both be mentionned ? 

## with bookdown 
**Easiest solution**
Automatic numbering and cross referencing
https://bookdown.org/yihui/bookdown/a-single-document.html

## without bookdown
It is possible to number figure and add caption without bookdown.
* Use a custom function and `fig.cap` chunk option
````r
# Incremental Figure Numbers

```{r setup, include=FALSE}
fn = local({
  i = 0
  function(x) {
    i <<- i + 1
    paste('Figure ', i, ': ', x, sep = '')
  }
})
```

```{r test-a, fig.cap=fn('this is one plot')}
plot(1:10)
```

```{r test-b, fig.cap=fn('another plot')}
plot(rnorm(10))
```
````
Source : [knitr example](https://github.com/yihui/knitr-examples/blob/master/070-caption-num.Rmd)

* Use [`captioner`](https://github.com/adletaw/captioner) 📦 

## Related SO question
* https://stackoverflow.com/questions/13848137/figure-captions-references-using-knitr-and-markdown-to-html

**Comment by mikey-harper** [comment]
Thanks for the suggestion. I definetely agree about explaining about **bookdown**.  

Interesting use case with the manual way of doing it and **captioner**. However, given the functionality of bookdown, I am not sure I can see a compelling enough reason to use them? I see this book as a good opportunity to remove some of the confusion around these topics so would only want to include them if there is a benefit.

Let me know if you are aware of any particular use cases where the latter might be useful.

**Comment by dr-harper** [comment]
I have added a section on numbered captions. See commit c009e5b089690214b04c7b2e9c275a772b10f426

The **captioner** package doesn't seem to be actively maintained anymore, and as per this old issue: https://github.com/adletaw/captioner/issues/29
