### ISSUE TITLE
How to cross-reference figures and tables in a rmarkdown document ? 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#29]
Use one of the special `bookdown` 📦 functions. 
Related to #25 about numbered figured

### Related SO questions

+ https://stackoverflow.com/questions/38861041/knitr-rmarkdown-latex-how-to-cross-reference-figures-and-tables

**Comment by dr-harper** [comment]
Good call. I think a really small example would be relevant showing a table and a figure. A common error seems to be that people forget to add captions to each. I've added this to my to-do list.

**Comment by dr-harper** [comment]
I have added a section on cross-referencing. Probably could do with further refinement at a later date.

https://dr-harper.github.io/rmarkdown-cookbook/cross-referencing-within-documents.html

**Comment by cderv** [comment]
https://stackoverflow.com/questions/17167140/chunk-reference-using-knitr-r-markdown-and-pandoc-pander
