### ISSUE TITLE
Include appendices after references

### ISSUE THREAD

**Issue by nathaneastwood** [dr-harper/rmarkdown-cookbook#40]
[How to include appendices after references](https://stackoverflow.com/questions/41532707/include-rmd-appendix-after-references/42258998#42258998) is a common question I see asked a lot.

**Comment by mikey-harper** [comment]
Great suggestion, thanks for opening this! There are some SO posts which relate to this but agree it would be useful to have a single source:

- https://stackoverflow.com/questions/16427637/pandoc-insert-appendix-after-bibliography?noredirect=1&lq=1
- https://stackoverflow.com/questions/33148325/how-to-insert-appendix-after-references-in-rmd-using-rstudio

Added to the to-do list 😄

**Comment by dr-harper** [comment]
I have added a first draft of this under 0a7e6b73477c20be0495ae8612149c15c2ed8033 . Thanks again for the suggestion.
