### ISSUE TITLE
How to hide message and warning of code chunk ? 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#48]
Already explained _in theory_ in [Rmarkdown definitive guide](https://bookdown.org/yihui/rmarkdown/r-code.html). 

Don't know if it worth mentioning with a use case and showcasing the IDE integration in 
![image](https://user-images.githubusercontent.com/6791940/46110628-869de880-c1e4-11e8-966b-66b8f3e489eb.png)

I let you close if we don't mentioned this in the cookbook. 

## Related SO question 
* https://stackoverflow.com/questions/15406028/suppressing-messages-in-knitr-rmarkdown

**Comment by cderv** [comment]
Topics mentioned in #12 
Sorry for double post

**Comment by yihui** [comment]
Closing this one in favor of #12...
