### ISSUE TITLE
Creating custom blocks

### ISSUE THREAD

**Issue by dr-harper** [dr-harper/rmarkdown-cookbook#50]
I really like including [custom blocks](https://bookdown.org/yihui/bookdown/custom-blocks.html) and I think that there could be a good opportunity to explain how to customise these within a book. For example:

- adding your own images
- where to store files 
- how to refer to these files in HTML/LaTeX

https://stackoverflow.com/questions/36293511/creating-custom-blocks-in-rstudios-bookdown

**Comment by cderv** [comment]
Topic related to #8

**Comment by cderv** [comment]
I think we can also find example of 📦 that extended rmarkdown using custom block. I have at least this one in mind [unilur](https://github.com/koncina/unilur) and its [custom box](http://koncina.github.io/unilur/articles/custom-boxes.html) and there should be others.

**Comment by dr-harper** [comment]
This is probably the most time-consuming section I have worked on so far! I wasn't happy with how messy the LaTeX code was so went about trying to find a better way of doing it. Think I got there in the end but my limited knowledge in writing LaTeX functions definitely wasn't helpful!

I have added the section in commit 
https://github.com/dr-harper/rmarkdown-cookbook/commit/c30015122cd821861237a96975b8e9bad59b8a97. You can view it here: https://dr-harper.github.io/rmarkdown-cookbook/custom-blocks.html

I considered adding the unilur package, but I struggled to fit it in naturally. I will keep a note of it for future reference and it might be appropriate.
