### ISSUE TITLE
Recipes about Parametrized report ? 

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#6]
Among my colleagues and other new Rmarkdown user, I saw that the parametrized rmarkdown option is underevaluated because not enough known. I know it is explained but a complete example could be helpful. For detail instructions, it would refers to the guide book

An example I have in mind is how to generate multiple reports from one Rmd using `params` argument in `render`, having all the function call inside one main script. It would focus on non-interactive use to illustrate the power of params.

What do you think ? 

### Related SO question

- [x] https://stackoverflow.com/questions/32479130/passing-parameters-to-r-markdown
- [x] https://stackoverflow.com/questions/18929782/how-can-i-pass-variables-into-an-r-markdown-rmd-file

**Comment by haozhu233** [comment]
Wow, @mikey-harper, enjoy your honeymoon~ 😆

**Comment by cderv** [comment]
This is covered in 9d7b54668c7cb0404617ab66707f244a9c0e3603 now.
See https://dr-harper.github.io/rmarkdown-cookbook/parameterized-reports.html
