### ISSUE TITLE
How to use verbatim code chunk or R inline expression

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#60]
How to do ``` `r expr` ``` or 
`````
```r
expr
```
`````
It is mentioned quickly [in the definitive guide](https://bookdown.org/yihui/rmarkdown/markdown-syntax.html#inline-formatting) but a separate quick recipe could be useful. 
There is [blog post](https://yihui.name/en/2017/11/knitr-verbatim-code-chunk/) about that, and it could be included in the book. 

So question: 

* https://stackoverflow.com/questions/20409172/how-to-display-verbatim-inline-r-code-with-backticks-using-rmarkdown

**Comment by dr-harper** [comment]
I have put together a draft based on the blog post here: https://github.com/dr-harper/rmarkdown-cookbook/blob/master/02-formatting/verbatim-code.Rmd. It is largely a shortened version of the blog post for now but I will tailor it another day when I have a bit more energy.

As a funny side note, I had to find a way of displaying the syntax used to display the verbatim code without it being processed by knitr! It felt like a never ending layer of code nesting!
