### ISSUE TITLE
How to add an item to bibliography without using it

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#66]
See this question
https://stackoverflow.com/questions/32946203/including-bibliography-in-rmarkdown-document-with-use-of-the-knitcitations

This is a pandoc feature
> If you want to include items in the bibliography without actually citing them in the body text, you can define a dummy nocite metadata field and put the citations there:
> ```` 
> ---
>nocite: |
>  @item1, @item2
>...
> 
>@item3
> ````
> In this example, the document will contain a citation for item3 only, but the bibliography will contain entries for item1, item2, and item3.

See https://pandoc.org/MANUAL.html

There may be other stuff to add to the cookbook about bibliography. We'll link issue if so.

**Comment by cderv** [comment]
About bibliography :
https://stackoverflow.com/questions/31221981/how-do-i-add-citations-and-a-bibliography-to-rpres-rmarkdown-presentations

If other, we may need a macro issue

**Comment by dr-harper** [comment]
Also https://github.com/rstudio/rmarkdown/issues/1096:

```
---
nocite: '@*'
...
```

This will display all items in the bibliography

**Comment by dr-harper** [comment]
Added the first two parts on the no cite [here](https://dr-harper.github.io/rmarkdown-cookbook/bibliographies-and-citations.html). Not included the third part yet on ** knitcitations** for RPres: this seems like quite an edge case, and the format has largely been replaced with the new formats. As said in the comments to the question:

> You're right; there are no bibliography options for .Rpres files. However, .Rpres predates, and is in most cases superseded by, the presentation formats available on R Markdown. For this reason it isn't receiving a lot of attention and it's likely that the gap between its capabilities and those of .Rmd is going to widen over time. .Rpres files don't render with Pandoc; they are rendered by an engine baked into the main RStudio binary. 

I will skip it for now, but leave the issue open in case we want to come back to it in the future.

**Comment by dr-harper** [comment]
I am going to close this issue as the only reason this was still open was because of the **knitcitations** package, which is covered in #155
