### ISSUE TITLE
Article about Bibliography and citations

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#70]
There is an article about [Bibliography and citations](
https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html) on the rmarkdown website that seems not to have been rewrote in the Definitive Guide.like [others](https://rmarkdown.rstudio.com/articles.html).  

The cookbook could be a good place to add this, and other related issues like #66

**Comment by dr-harper** [comment]
I have integrated a lot of the details from this into the section on bibliographies: https://dr-harper.github.io/rmarkdown-cookbook/bibliographies-and-citations.html

I am still trying to be careful on what to include. Generally I ask myself "how could this be useful to someone?". This is why I decided not to mention all the different file types which can be used for bibliographies. Happy to explain this in the future if we can find a practical reason to do so though.

See commit 4fdce0c139d971ab4614cbdca9f9a1aa2a6ffdbe
