### ISSUE TITLE
Scrollable code output

### ISSUE THREAD

**Issue by nathaneastwood** [dr-harper/rmarkdown-cookbook#75]
I'm not sure if this is something you would want to include?

https://github.com/nathaneastwood/r-markdown-scroll

It adds a scroll bar to R code chunk output so your html documents aren't made excessively long.

**Comment by dr-harper** [comment]
That's cool! I could definitely see this fitting into a section on CSS customisation.

Is there any way you could combine this with a custom knitr hook so that the scroll option could be controlled on a chunk-by-chunk basis?   https://stackoverflow.com/questions/37944197/add-a-css-class-to-single-code-chunks-in-rmarkdown

**Comment by nathaneastwood** [comment]
So are you thinking I could add a class based on the length of the R output? And then set a user-specified output length (e.g. `max_length = 300px`)?

The other thing to consider is that my code at the moment doesn't work for **bookdown** as I think the css targets are slightly different so a hook might be a better way to represent the initial work I've done. I could then potentially package it up, simply write a wrapper around the hook and call it with a function.

**Comment by dr-harper** [comment]
Letting a user set a max length would be a lovely feature. As a basic example of what I originally meant, you could potentially assign the syle via the `class.output` chunk option:

````
---
output: html_document
---

```{css}
.pre {
  max-height: 300px;
  float: left;
  width: 910px;
  overflow-y: auto;
}
```

```{r, class.output = "pre"}
cars
```
````

It would be cool if we could get to a position where we could set the setting of the code chunk in the header of the code chunk:

````
```{r, max_length = 300px}
cars
```
````

Knitr hooks are an area I have been meaning to learn for a while, so may look at playing around with this for an example of the cookbook. But let me know if you work on it at all :)

**Comment by dr-harper** [comment]
I ended up designing a knitr hook!

---
title: "Untitled"
output: html_document
---

````
```{r, include=FALSE}

knitr::knit_hooks$set(output = function(x, options){
  if(!is.null(options$max_height)){
    paste('<pre style = "max-height:', options$max_height, '; float: left; width: 910px; overflow-y: auto; color:black;">', x, "</pre>", sep = "")
  }else{
    x
  }
  
})
  
  
```

```{r max_height = "200px"}
cars
```
````

**Comment by dr-harper** [comment]
I have added two sections on this concept in commit 5dc6258f895bcc49699358f18e59b00f2cb443d9. One comes under the HTML chapter and I bring it up again within the Hooks chapter. 

Still working out how to structure the book, and this may be joined together at a later date.

Keep the useful ideas coming 👍

**Comment by nathaneastwood** [comment]
I added it to a new package called [hooks](https://github.com/nathaneastwood/hooks). I imagine I could add more in here, for example [adding verbatim chunks](https://rmarkdown.rstudio.com/articles_verbatim2.html). The function could potentially be improved as well to automatically handle bookdown which has slightly different css tags.

**Comment by cderv** [comment]
I find the idea of a package showcasing hooks from the wild is a good idea! Thanks !

**Comment by cderv** [comment]
Added in fc10a47f1eb423526eb1e639ace1d56a37a0cbff
