### ISSUE TITLE
Knitr hooks: showing the first n lines of the output

### ISSUE THREAD

**Issue by dr-harper** [dr-harper/rmarkdown-cookbook#76]
This has a good answer on to use knitr hooks:

https://community.rstudio.com/t/showing-only-the-first-few-lines-of-the-results-of-a-code-chunk/6963

Originally linked from SO here: https://community.rstudio.com/t/showing-only-the-first-few-lines-of-the-results-of-a-code-chunk/6963

**Comment by cderv** [comment]
Nice example ! 
Correct SO link : https://stackoverflow.com/questions/23114654/knitr-output-hook-with-an-output-lines-option-that-works-like-echo-26

**Comment by dr-harper** [comment]
@nathaneastwood another candidate for your package!

**Comment by nathaneastwood** [comment]
I've added this functionality in https://github.com/nathaneastwood/knitrhooks/commit/9a879facaec3e78048e6427697491c9ab7bf674f :) thanks for the suggestion.

**Comment by cderv** [comment]
Related to this knitr example
https://github.com/yihui/knitr-examples/blob/master/052-suppress-output.Rmd

**Comment by cderv** [comment]
Reminder: show that it works also for non R chunk

## result

``` r
library(knitr)
# the default output hook
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  if (!is.null(n <- options$out.lines)) {
    x = unlist(stringr::str_split(x, '\n'))
    if (length(x) > n) {
      # truncate the output
      x = c(head(x, n), '....\n')
    }
    x = paste(x, collapse = '\n') # paste first n lines together
  }
  hook_output(x, options)
})
```

``` bash
for i in {1..10}; do echo $i; done
```

    ## 1
    ## 2
    ## 3
    ## 4
    ## 5
    ## 6
    ## 7
    ## 8
    ## 9
    ## 10

``` bash
for i in {1..10}; do echo $i; done
```

    ## 1
    ## 2
    ## 3
    ## 4
    ## 5
    ....

### source

````
---
output:
  github_document: 
    html_preview: false
---

```{r setup}
library(knitr)
# the default output hook
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  if (!is.null(n <- options$out.lines)) {
    x = unlist(stringr::str_split(x, '\n'))
    if (length(x) > n) {
      # truncate the output
      x = c(head(x, n), '....\n')
    }
    x = paste(x, collapse = '\n') # paste first n lines together
  }
  hook_output(x, options)
})
```

```{bash}
for i in {1..10}; do echo $i; done
```

```{bash, out.lines=5}
for i in {1..10}; do echo $i; done
```
````

**Comment by cderv** [comment]
added in 876bca3facedd30b8cc48cd9c1c86020d1e2adf9
