### ISSUE TITLE
How to customise knit button in RStudio

### ISSUE THREAD

**Issue by cderv** [dr-harper/rmarkdown-cookbook#88]
I often stumbled upon this trick to define a custom function in the `knit` yaml parameter. 
This allow to modify the behaviour of the knit button. I don't if it is documented somewhere but there are some question about that

* https://stackoverflow.com/questions/28894515/rmarkdown-directing-output-file-into-a-directory

**Comment by dr-harper** [comment]
This would fit nicely in a section with R Studio Customisation along with

https://github.com/dr-harper/rmarkdown-cookbook/issues/80

**Comment by cderv** [comment]
Some additions in 4b2d2e4023ee561ab3bef21df1e7b0cfd62e3697  and this is now covered
