### ISSUE TITLE
Adding numbered code chunks in HTML

### ISSUE THREAD

**Issue by dr-harper** [dr-harper/rmarkdown-cookbook#91]
I stumbled across this, and liked it as an example of using CSS for customising the HTML output:

https://stackoverflow.com/questions/48914212/numbered-code-chunks-in-rmarkdown

**Comment by cderv** [comment]
Related but not real answer there
https://stackoverflow.com/questions/22329685/how-to-display-line-numbers-in-rmarkdown-html-and-pdf

**Comment by cderv** [comment]
Added in 0b6f13034594e2702ada740b173301ac4bceff50
